name: Install and Configure xrdp with ngrok

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up ngrok
      run: |
        if ! command -v ngrok &> /dev/null; then
          wget --no-check-certificate https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xzf ngrok-v3-stable-linux-amd64.tgz
          rm ngrok-v3-stable-linux-amd64.tgz
        fi

    - name: Install xrdp
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp

    - name: Set root password
      run: |
        echo "root:xrdp2024" | sudo chpasswd

    - name: Launch ngrok and xrdp
      run: |
        ./ngrok authtoken "2caHmdmIRjB4ANpwvKxjOYuH56N_2NnL8f3pYFBrzTvUVVPzy"
        ./ngrok tcp 3389 &
        sudo xrdp &
