name: XRDP with ngrok

on:
  workflow_dispatch:  # يشغل العملية يدويًا عند الطلب اليدوي
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"  # يشغل العملية تلقائيًا كل 30 دقيقة

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Xrdp for no password login
      run: |
        sudo apt update && sudo apt install xrdp -y
        sudo sed -i 's/autorun=xfreerdp/#autorun=xfreerdp/g' /etc/xrdp/startwm.sh
        sudo systemctl restart xrdp

    - name: Download and extract ngrok
      run: |
        wget -q -O ngrok.zip "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip"
        unzip -q ngrok.zip

    - name: Set up ngrok tunnel
      run: |
        ./ngrok authtoken 2caHmdmIRjB4ANpwvKxjOYuH56N_2NnL8f3pYFBrzTvUVVPzy
        ./ngrok tcp 3389 &

    - name: Wait for ngrok tunnel to be established
      run: sleep 10  # ينتظر ثواني للسماح بإنشاء النفق

    - name: Get ngrok public URL
      id: ngrok
      run: echo "::set-output name=url::$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"

    - name: Display ngrok public URL
      run: echo "Ngrok public URL: ${{ steps.ngrok.outputs.url }}"

    - name: Connect to XRDP session
      run: |
        sudo apt install -y freerdp2-x11
        xfreerdp /v:${{ steps.ngrok.outputs.url }} --no-nla --ignore-certificate -u user -p ""  # توصيل مباشر بدون كلمة مرور
