name: XRDP with ngrok

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install and start xrdp service
      run: |
        sudo apt update && sudo apt install xrdp -y && sudo systemctl start xrdp

    - name: Download ngrok
      run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip

    - name: Extract ngrok
      run: |
        unzip ngrok.zip
        ./ngrok/ngrok authtoken 2caHmdmIRjB4ANpwvKxjOYuH56N_2NnL8f3pYFBrzTvUVVPzy
        ./ngrok/ngrok tcp 3389
