name: Run Ubuntu Machine

on:
  workflow_dispatch: # يمكن تشغيل العمل يدوياً عبر واجهة المستخدم
  schedule:
    - cron: "*/30 * * * *" # يمكن تشغيل العمل تلقائياً كل 30 دقيقة

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download ngrok
      run: |
        wget -O ngrok.tgz "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz"
        tar -xf ngrok.tgz

    - name: Run bash script
      run: TERM=xterm bash nomachinewindows10

    - name: Sleep for 30 minutes
      run: sleep 1800
